config/routes.rb
Rails.application.routes.draw do

    get 'admin' => 'admin#index'

controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
end

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products
root 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helloo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'  >
    <div id ="banner">
        <%= image_tag( "logo.jpg")%>
        <%= @page_title || "Restaurant Management"%>
        <%= button_to 'SignUp', new_user_path,:method => :get %>
    </div>
    <div id="columns">
        <div id="side">
            <%if @cart%>
          <div id="cart">
              <%= render @cart  %>
          <%end%>
              </div>
            <ul>
                <li><a href="www.fsf">Home</a></li>
                  <li><a href="www.fsf">FAQ</a></li>
                 <li><a href="www.fsf">News</a></li>
                  <li><a href="www.fsf">Contact</a></li>
            </ul>

            <%if session[:user_id]%>
                <ul>
                    <li><%= link_to 'Orders', orders_path %></li>
                    <li><%= link_to 'Products', products_path%></li>
                    <li><%= link_to 'Users', users_path %></li>
                </ul>
                <%=button_to 'Logout', logout_path, method: :delete%>
                <%= button_to 'Login', login_path%>
                
            <%end%>
        </div>

    <div id="main"  >
        <%= yield %>
    </div>
    </div>
</body>
</html>